# Run after pkgdown::build_site() to verify llms.txt was generated,
# or generate it manually if pkgdown doesn't support it natively.
# Usage: source("tools/build_llms.R") from project root, or
#        Rscript tools/build_llms.R

# Check if pkgdown already generated llms.txt
if (file.exists("docs/llms.txt")) {
  message("llms.txt already generated by pkgdown at docs/llms.txt")
} else {
  # Generate a simple llms.txt index
  site_url <- "https://noamross.github.io/airtable2/"
  ref_pages <- list.files("docs/reference", pattern = "\\.html$", full.names = FALSE)
  article_pages <- list.files("docs/articles", pattern = "\\.html$", full.names = FALSE)

  lines <- c(
    "# airtable2",
    "",
    "> httr2-based Airtable REST client for R with DBI interface, backup/restore, and special type support.",
    "",
    "## Docs",
    "",
    paste0("- [Getting Started](", site_url, "articles/airtable2.html): Installation, authentication, API limits, full walkthrough"),
    paste0("- [Special Types](", site_url, "articles/special-types.html): S3 type classes, attachments, linking records"),
    paste0("- [Metadata & Backup](", site_url, "articles/metadata-backup.html): Schema, air_meta, air_dump/air_restore"),
    "",
    "## Reference",
    "",
    paste0("- [", gsub("\\.html$", "", ref_pages), "](", site_url, "reference/", ref_pages, ")")
  )

  writeLines(lines, "docs/llms.txt")
  message("Generated docs/llms.txt")
}

# Generate llms-full.txt: concatenate all reference pages as markdown
# (simplified: just list all pages with their URLs for now)
if (!file.exists("docs/llms-full.txt")) {
  site_url <- "https://noamross.github.io/airtable2/"
  lines_full <- c(
    "# airtable2 — Full Reference",
    "",
    paste0("Source: ", site_url),
    "",
    "All reference pages:",
    paste0("- ", site_url, "reference/", list.files("docs/reference", pattern = "\\.html$")),
    "",
    "All articles:",
    paste0("- ", site_url, "articles/", list.files("docs/articles", pattern = "\\.html$"))
  )
  writeLines(lines_full, "docs/llms-full.txt")
  message("Generated docs/llms-full.txt")
}
