# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: macos-latest,   r: 'release', env: 'standard-testing'}
          - {os: windows-latest, r: 'release', env: 'standard-testing'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release', env: 'standard-testing'}
          - {os: ubuntu-latest,   r: 'release', env: 'standard-testing'}
          - {os: ubuntu-latest,   r: 'oldrel-1', env: 'standard-testing'}
          - {os: ubuntu-latest,   r: 'release', env: 'protected-testing'}

    environment: ${{ matrix.config.env }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        env:
          AIRTABLE_WORKSPACE_ID: ${{ secrets.AIRTABLE_WORKSPACE_ID }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_TEST_SCHEMA: ${{ vars.AIRTABLE_TEST_SCHEMA }}
          AIRTABLE_TEST_LIVE: ${{ vars.AIRTABLE_TEST_LIVE }}
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
